package com.sloths.speedy.shortsounds.model;

import android.graphics.PointF;
import android.media.audiofx.Equalizer;
import android.util.Log;

/**
 * Equalizer Effect. This class provides a wrapper around the existing Android Equalizer
 * effect class.
 */
public class EqEffect extends Effect {
    // these INDEX constants are for accessing the values encoded in the string after
    // it has been split by "."
    private static final int INDEX_ACTIVE = 1;
    private static final int INDEX_BAND_LEVELS = 2;
    private static final int NUM_BANDS = 2;
    private static final String ON = "ON";
    public static final float DEFAULT_Y = 0;
    public static final float DEFAULT_X1 = 0.3f;
    public static final float DEFAULT_X2 = 0.7f;
    private PointF[] eqPoints;
    // TODO: Change defaulted band levels to band levels generated by conversion from points

    // Constructor used when loading a track from a recorded file
    public EqEffect() {
        PointF lo = new PointF(DEFAULT_X1, DEFAULT_Y);
        PointF hi = new PointF(DEFAULT_X2, DEFAULT_Y);
        this.eqPoints = new PointF[]{lo, hi};
        effect = new Equalizer(0, 0);
        effect.setEnabled( false );
        setEffectProperties();
        repInvariant();
    }

    // Constructor used when loading an effect from the database
    public EqEffect(String effectVals) {
        this();
        if ( !effectVals.equals( "NULL" ) ) {
            // Parse string from DB to get point vals & on/off
            // Stored in DB as "ON/OFF:float,float,float,float"
            String[] params = effectVals.split(":");
            effect.setEnabled( params[0].equals(ON) );
            String[] pointVals = params[1].split(",");
            eqPoints = new PointF[2];
            eqPoints[0] = new PointF(new Float(pointVals[0]), new Float(pointVals[1]));
            eqPoints[1] = new PointF(new Float(pointVals[2]), new Float(pointVals[3]));
            setEffectProperties();
        }
        repInvariant();
    }

    // Stored in Track table for effect params and on off
    public String encodeParameters() {
        if (eqPoints == null) {
            return "NULL";
        }
        String retVal = new String();
        if ( getEnabled() ) {
            retVal += "ON";
        } else {
            retVal += "OFF";
        }
        retVal += ":";
        retVal += eqPoints[0].x + ",";
        retVal += eqPoints[0].y + ",";
        retVal += eqPoints[1].x + ",";
        retVal += eqPoints[1].y;
        return retVal;
    }

    /**
     * Set the properties of the Equalizer effect class.
     */
    private void setEffectProperties() {
        Equalizer.Settings settings = convertParamsToSettings();
        Equalizer eq = (Equalizer) effect;
        // TODO: remove the preset once conversion is complete
        Log.d("EFFECTS", "EQ using preset " + eq.getPresetName( (short) 5 ) );
//        eq.usePreset( (short) 9 );  // 9 = Rock, 3 = Flat
//        eq.setProperties( settings );
    }

    /**
     * Convert the EqEffect parameters into an Equalizer.Settings object
     * that is understood by android.
     * @return
     */
    private Equalizer.Settings convertParamsToSettings() {
        // TODO
        return new Equalizer.Settings();
    }

    /**
     * Enable the effect.
     */
    public void enable() {
        effect.setEnabled(true);
    }

    /**
     * Disable the effect.
     */
    public void disable() {
        effect.setEnabled(false);
    }

    public String getTitleString() {
        return "Equalizer";
    }

    /**
     * For getting point values to be used in UI
     * @return
     */
    public PointF[] getPointVals() {
//        Log.d("EqEfect", "Returning eq effect values...");
        if (eqPoints == null) {
//            Log.d("EqEffect", "null eq effect values");
        } else {
//            Log.d("EqEffect", eqPoints[0].x + ", " + eqPoints[0].y + "),(" + eqPoints[1].x + ", " + eqPoints[1].y + ")");
        }
        return eqPoints;
    }

    /**
     * For setting the point values coming from UI
     * @param points
     */
    public void setPointVals(PointF[] points) {
//        Log.d("EqEfect", "Setting eq effect values to...");
        if (eqPoints == null) {
            this.eqPoints = new PointF[2];
        }
        this.eqPoints[0] = points[0];
        this.eqPoints[1] = points[1];
//        Log.d("EqEffect", eqPoints[0].x + ", " + eqPoints[0].y + "),(" + eqPoints[1].x + ", " + eqPoints[1].y + ")");
        setEffectProperties();
    }

    /**
     * Resets points for when cancel/back is clicked
     */
    public void resetVals() {
        PointF lo = new PointF(DEFAULT_X1, DEFAULT_Y);
        PointF hi = new PointF(DEFAULT_X2, DEFAULT_Y);
        this.eqPoints = new PointF[]{lo, hi};
    }

    /**
     * A representation invariant of an EQ effect that holds the points and bands
     * for the EQ UI and EQ effect.
     */
    private void repInvariant() {
        if (effect == null) throw new AssertionError("Where is my effect?");
    }


}
